// Package banner renders the Lunatic header: the word LUNATIC in a 5x7 pixel
// font next to a five-pointed star drawn with the letters of "lunatic".
package banner

import (
	"io"
	"strings"

	"github.com/lunalully/lunatic/internal/term"
)

// pixel is the character used for each lit pixel of the word.
const pixel = "▓"

// glyphs is the 5x7 bitmap font ('#' = lit) for the letters of LUNATIC.
var glyphs = map[byte][7]string{
	'L': {"#....", "#....", "#....", "#....", "#....", "#....", "#####"},
	'U': {"#...#", "#...#", "#...#", "#...#", "#...#", "#...#", ".###."},
	'N': {"#...#", "##..#", "##..#", "#.#.#", "#..##", "#..##", "#...#"},
	'A': {".###.", "#...#", "#...#", "#####", "#...#", "#...#", "#...#"},
	'T': {"#####", "..#..", "..#..", "..#..", "..#..", "..#..", "..#.."},
	'I': {"#####", "..#..", "..#..", "..#..", "..#..", "..#..", "#####"},
	'C': {".####", "#....", "#....", "#....", "#....", "#....", ".####"},
}

// Word is the pixel-font rendering of LUNATIC: 7 rows, 41 columns.
var Word = buildWord("LUNATIC")

func buildWord(s string) []string {
	rows := make([]string, 7)
	for i := 0; i < len(s); i++ {
		g := glyphs[s[i]]
		for r := range rows {
			if i > 0 {
				rows[r] += " "
			}
			for _, c := range g[r] {
				if c == '#' {
					rows[r] += pixel
				} else {
					rows[r] += " "
				}
			}
		}
	}
	return rows
}

// Star is a five-pointed star outline whose stroke is the letters of
// "lunatic" cycled in order. Generated by gen/star.go
// (go run internal/banner/gen/star.go -r 6.8 -w 0.7 -t 0.5 -h 12 -c 27); the
// generator is not part of the binary.
var Star = []string{
	"            lun",
	"           aticl",
	"          unaticl",
	"         unat iclu",
	"naticlunatic   lunaticlunat",
	"icluna               ticlun",
	"   aticl           unati",
	"      clun       atic",
	"      lun    a    tic",
	"      lun aticlun ati",
	"     clunati   clunati",
	"    clunat       icluna",
}

const (
	gap     = 4
	tagline = "Passive Subdomain Recon  v"
)

// width in columns (runes) of the widest row.
func width(rows []string) int {
	w := 0
	for _, r := range rows {
		if n := len([]rune(r)); n > w {
			w = n
		}
	}
	return w
}

func pad(s string, w int) string {
	if n := len([]rune(s)); n < w {
		return s + strings.Repeat(" ", w-n)
	}
	return s
}

// Render returns the banner text. lvl None yields plain text with no ANSI.
func Render(version string, lvl term.Level) string {
	left := make([]string, len(Star))
	off := (len(Star) - (len(Word) + 2)) / 2 // word + blank + tagline block
	for i := range Word {
		left[off+i] = Word[i]
	}
	if t := off + len(Word) + 2; t < len(left) {
		left[t] = tagline + version
	}
	lw := width(Word)
	if n := len([]rune(tagline + version)); n > lw {
		lw = n
	}
	var b strings.Builder
	b.WriteString("\n")
	for i := range Star {
		line := strings.TrimRight(pad(left[i], lw)+strings.Repeat(" ", gap)+Star[i], " ")
		b.WriteString("  " + term.Paint(lvl, "orange", line) + "\n")
	}
	b.WriteString("\n")
	return b.String()
}

// Print writes the banner to w (callers pass stderr, only when it is a TTY
// and not --silent).
func Print(w io.Writer, version string, lvl term.Level) {
	io.WriteString(w, Render(version, lvl))
}
